version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./auth_system/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"

  backend:
    container_name: backend_fastapi
    build: ./auth_system
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
#      - .env
      - ./auth_system/.env

  redis:
    image: redis:7.2.4-alpine
    hostname: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: