from notes.note_generate.create_note import generate_note

data_example = {
    "selectedInsurance": "fdn",
    "selectedLevelOfCare": "Detox",
    "selectedNoteType": "Physician Note",
    "selectedNoteFormat": "Dap Note",
    "patient_name": "John Doe",
    "group_size": 15,  # used in group_note
    "submission_deadline": "2024-05-20",  # used in ur_note
    "time": "10:00 AM",  # used in nursing_note
    "acuteIntoxicationAndWithdrawalPotential": ["alcohol smell", "confusion", "Red skin", "slurred speech", "pupil constriction"],
    "biomedicalConditionAndComplications": ["liver disease", "high level of bilirubin"],
    "emotionalBehavior": ["grief", "eating disorders"],
    "chooseIfHePatientHasAnyKindOfRisckyBehavior": ["cutting", "psychosis"],

}

def camel_case_to_sentence(text):

    # Split the string at each uppercase letter, except for the first character
    words = [text[0].upper()]  # Start with the first character capitalized
    for char in text[1:]:
        if char.isupper():
            words.append(' ')  # Add a space before each uppercase letter in the middle of the string
        words.append(char.lower())  # Add the character in lowercase

    # Join all parts into a single string
    sentence = ''.join(words)

    return sentence


def format_dict_to_text(data):
    # Initialize an empty list to hold the formatted text
    formatted_text = []

    # Iterate through the dictionary items
    for key, values in data.items():
        # Check if the value is a list and process accordingly
        if isinstance(values, list):
            # Assume all items in the list are strings for simplicity
            value_string = ", ".join(values)
            # Append the formatted string to the list
            formatted_text.append(f"{camel_case_to_sentence(key)}: {value_string}")

    # Join all formatted text into a single string, separated by a semicolon
    output_text = "; \n".join(formatted_text)

    return output_text
# print(format_dict_to_text(data_example))

data_example = {
    "selectedInsurance": "fdn",
    "selectedLevelOfCare": "Detox",
    "selectedNoteType": "Physician Note",
    "selectedNoteFormat": "Dap Note",
    "patient_name": "John Doe",
    "group_size": 15,  # used in group_note
    "submission_deadline": "2024-05-20",  # used in ur_note
    "time": "10:00 AM",  # used in nursing_note
    "acuteIntoxicationAndWithdrawalPotential": ["alcohol smell", "confusion", "Red skin", "slurred speech", "pupil constriction"],
    "biomedicalConditionAndComplications": ["liver disease", "high level of bilirubin"],
    "emotionalBehavior": ["grief", "eating disorders"],
    "chooseIfHePatientHasAnyKindOfRisckyBehavior": ["cutting", "psychosis"],

}


async def handle_note_data(data: dict):
    if data["selectedInsurance"] == "Magelan":
        if data["selectedLevelOfCare"] in "Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...

        elif data["selectedLevelOfCare"] in "Residential Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Day Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Intensive Outpatient (IOP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Ambulatory Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        else:
            ...
    elif data["selectedInsurance"] == "Cigna and Evernorth:":
        if data["selectedLevelOfCare"] in "Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...

        elif data["selectedLevelOfCare"] in "Residential Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Day Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Intensive Outpatient (IOP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Ambulatory Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        else:
            ...
    elif data["selectedInsurance"] == "Optum and United Healthcare":
        if data["selectedLevelOfCare"] in "Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...

        elif data["selectedLevelOfCare"] in "Residential Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Day Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Intensive Outpatient (IOP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Ambulatory Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        else:
            ...
    elif data["selectedInsurance"] == "Aetna":
        if data["selectedLevelOfCare"] in "Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...

        elif data["selectedLevelOfCare"] in "Residential Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Day Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Intensive Outpatient (IOP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Ambulatory Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        else:
            ...
    elif data["selectedInsurance"] == "BCBS Blue Cross Blue Shild":
        if data["selectedLevelOfCare"] in "Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...

        elif data["selectedLevelOfCare"] in "Residential":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Partial Hospitalization Program (PHP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Intensive Outpatient (IOP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        else:
            ...
    else:
        if data["selectedLevelOfCare"] in "Detox":
            if data["selectedNoteType"] in "Physician Note":
                note = (f'Create note for {data["patient_name"]} using some insurance company templates. This must be {data["selectedNoteType"]} type. '
                        f'And clinically managed {data["selectedLevelOfCare"]} level of care. \n'
                        f'Also include in the note this characteristic and symptoms: {format_dict_to_text(data)}.'
                        f"\nYou must write note in {data['selectedNoteFormat']} note format")
                print(note)
                return await generate_note(messages=note)
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...

        elif data["selectedLevelOfCare"] in "Residential Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Day Treatment":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Intensive Outpatient (IOP)":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        elif data["selectedLevelOfCare"] in "Ambulatory Detox":
            if data["selectedNoteType"] in "Physician Note":
                ...
            elif data["selectedNoteType"] in "Group Note":
                ...
            elif data["selectedNoteType"] in "Ancillary Progress Not":
                ...
            elif data["selectedNoteType"] in "UR Note":
                ...
            elif data["selectedNoteType"] in "Nursing Note":
                ...
            elif data["selectedNoteType"] in "Individual Note":
                ...
            else:
                ...
        else:
            ...


# await handle_note_data(data_example)
